backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Body text", name: "body", widget: "markdown"}
      - file: "src/pages/about/index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Body text", name: "body", widget: "markdown"}
      - file: "src/pages/submit-personal-story/index.md"
        label: "Submit Personal Story Page"
        name: "submit personal story"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "submit-personal-story-page"}
          - {label: "Subtitle", name: "body", widget: "markdown"}
      - file: "src/pages/contact/index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Subtitle", name: "body", widget: "markdown"}
  - name: "stories"
    label: "Stories" # Used in the UI
    preview_path: "{{slug}}"
    folder: "src/pages/read-stories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "story"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Who", name: "who", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
  - name: "resources"
    label: "Resources" # Used in the UI
    preview_path: "{{slug}}"
    folder: "src/pages/resources" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "resource"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", options: ['toolkit', 'videos', 'endorsers'], widget: "select", hint: "For toolkit resources, use the file upload to upload a pdf. For endorsers or videos, use the URL field to add the link"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Url", name: "url", required: false, widget: "string", hint: "If you're using a youtube link, make sure to use the embed link. It should start with youtube.com/embed/ and then have some random letters after it"}
      - {label: "Resource", name: "resource", required: false, widget: "file", hint: "All resources need to be pdfs"}
  - name: "media coverage"
    label: "Media Coverage" # Used in the UI
    preview_path: "{{slug}}"
    folder: "src/pages/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Url", name: "url", widget: "string"}
